services:
  postgres:
    image: postgres:16
    container_name: mots-fleches-postgres
    environment:
      POSTGRES_USER: motsfleches
      POSTGRES_PASSWORD: motsfleches
      POSTGRES_DB: motsfleches
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
