import { buildGame } from 'grille-engine';
import { GridDefinition, GridSolution } from 'shared';

export const MOCK_GRID_6: GridDefinition = {
  width: 6,
  height: 6,
  cells: [
    {
      kind: 'clue',
      entries: [
        { definition: 'Sans vêtements', arrow: 'right' },
        { definition: 'Dans le squelette', arrow: 'down' },
      ],
    },
    { kind: 'letter' },
    { kind: 'letter' },
    {
      kind: 'clue',
      entries: [
        { definition: 'Article défini', arrow: 'right' },
        { definition: 'Métal précieux', arrow: 'down' },
      ],
    },
    { kind: 'letter' },
    { kind: 'letter' },
    { kind: 'letter' },
    {
      kind: 'clue',
      entries: [
        { definition: 'Première note de musique', arrow: 'right' },
        { definition: 'Quatre côtés égaux', arrow: 'down-right' },
      ],
    },
    { kind: 'letter' },
    { kind: 'letter' },
    {
      kind: 'clue',
      entries: [
        { definition: 'Voyelle', arrow: 'right' },
        { definition: 'Dieu solaire égyptien', arrow: 'down' },
      ],
    },
    { kind: 'letter' },
    { kind: 'letter' },
    { kind: 'letter' },
    { kind: 'letter' },
    { kind: 'letter' },
    { kind: 'letter' },
    { kind: 'letter' },
    {
      kind: 'clue',
      entries: [
        { definition: 'Pronom personnel', arrow: 'right' },
        { definition: 'Conjonction de coordination', arrow: 'down' },
      ],
    },
    { kind: 'letter' },
    { kind: 'letter' },
    {
      kind: 'clue',
      entries: [
        { definition: 'Forme de « avoir »', arrow: 'right' },
        { definition: 'Choix entre deux choses', arrow: 'down' },
      ],
    },
    { kind: 'letter' },
    { kind: 'letter' },
    { kind: 'letter' },
    {
      kind: 'clue',
      entries: [
        { definition: 'Négation appariée', arrow: 'right-down' },
        { definition: 'Première voyelle', arrow: 'down' },
      ],
    },
    { kind: 'letter' },
    { kind: 'letter' },
    {
      kind: 'clue',
      entries: [
        { definition: 'Note de musique', arrow: 'right-down' },
        { definition: 'Lettre', arrow: 'down' },
      ],
    },
    { kind: 'letter' },
    { kind: 'letter' },
    { kind: 'letter' },
    { kind: 'letter' },
    { kind: 'letter' },
    { kind: 'letter' },
    { kind: 'letter' },
  ],
};

export const MOCK_GRID_6_SOLUTION: GridSolution = {
  letters: [
    '',
    'N',
    'U',
    '',
    'L',
    'E',
    'O',
    '',
    'D',
    'O',
    '',
    'A',
    'S',
    'C',
    'A',
    'R',
    'R',
    'E',
    '',
    'T',
    'U',
    '',
    'A',
    'I',
    'E',
    '',
    'N',
    'O',
    '',
    'R',
    'T',
    'A',
    'I',
    'U',
    'T',
    'E',
  ],
};

export const MOCK_GRID_10: GridDefinition = {
  width: 10,
  height: 10,
  cells: [
    {
      kind: 'clue',
      entries: [
        { definition: 'Ancien pronom démonstratif', arrow: 'right' },
        { definition: 'Rubriques journalistiques', arrow: 'right-down' },
      ],
    },
    { kind: 'letter' },
    { kind: 'letter' },
    {
      kind: 'clue',
      entries: [
        { definition: 'Environ 3,14', arrow: 'right' },
        { definition: 'Qui donne de bons résultats', arrow: 'right-down' },
      ],
    },
    { kind: 'letter' },
    { kind: 'letter' },
    {
      kind: 'clue',
      entries: [
        { definition: 'Sel, en latin', arrow: 'right' },
        { definition: 'Résout', arrow: 'right-down' },
      ],
    },
    { kind: 'letter' },
    { kind: 'letter' },
    { kind: 'letter' },
    { kind: 'clue', entries: [{ definition: 'Exclamation de rire', arrow: 'right' }] },
    { kind: 'letter' },
    { kind: 'letter' },
    { kind: 'clue', entries: [{ definition: 'Conjonction de coordination', arrow: 'right' }] },
    { kind: 'letter' },
    { kind: 'letter' },
    { kind: 'clue', entries: [{ definition: 'Tente, ose', arrow: 'right' }] },
    { kind: 'letter' },
    { kind: 'letter' },
    { kind: 'letter' },
    { kind: 'clue', entries: [{ definition: 'Petit ruisseau', arrow: 'right' }] },
    { kind: 'letter' },
    { kind: 'letter' },
    { kind: 'clue', entries: [{ definition: 'Dieu solaire égyptien', arrow: 'right' }] },
    { kind: 'letter' },
    { kind: 'letter' },
    { kind: 'clue', entries: [{ definition: 'Lu, au féminin', arrow: 'right' }] },
    { kind: 'letter' },
    { kind: 'letter' },
    { kind: 'letter' },
    { kind: 'clue', entries: [{ definition: 'Pronom indéfini', arrow: 'right' }] },
    { kind: 'letter' },
    { kind: 'letter' },
    { kind: 'clue', entries: [{ definition: 'Vieille exclamation de dégoût', arrow: 'right' }] },
    { kind: 'letter' },
    { kind: 'letter' },
    { kind: 'clue', entries: [{ definition: 'Sans aspérités', arrow: 'right' }] },
    { kind: 'letter' },
    { kind: 'letter' },
    { kind: 'letter' },
    { kind: 'clue', entries: [{ definition: 'Adverbe de négation', arrow: 'right' }] },
    { kind: 'letter' },
    { kind: 'letter' },
    { kind: 'clue', entries: [{ definition: 'Pronom personnel', arrow: 'right' }] },
    { kind: 'letter' },
    { kind: 'letter' },
    { kind: 'clue', entries: [{ definition: 'Lettre grecque', arrow: 'right' }] },
    { kind: 'letter' },
    { kind: 'letter' },
    { kind: 'letter' },
    { kind: 'clue', entries: [{ definition: 'Pronom sujet masculin', arrow: 'right' }] },
    { kind: 'letter' },
    { kind: 'letter' },
    { kind: 'clue', entries: [{ definition: 'Note de musique', arrow: 'right' }] },
    { kind: 'letter' },
    { kind: 'letter' },
    { kind: 'clue', entries: [{ definition: 'Courroux', arrow: 'right' }] },
    { kind: 'letter' },
    { kind: 'letter' },
    { kind: 'letter' },
    { kind: 'clue', entries: [{ definition: 'Énergie vitale en Chine', arrow: 'right' }] },
    { kind: 'letter' },
    { kind: 'letter' },
    { kind: 'clue', entries: [{ definition: 'Mon, au féminin', arrow: 'right' }] },
    { kind: 'letter' },
    { kind: 'letter' },
    { kind: 'clue', entries: [{ definition: 'Passé simple de « oser »', arrow: 'right' }] },
    { kind: 'letter' },
    { kind: 'letter' },
    { kind: 'letter' },
    { kind: 'clue', entries: [{ definition: 'Pronom indéfini', arrow: 'right' }] },
    { kind: 'letter' },
    { kind: 'letter' },
    { kind: 'clue', entries: [{ definition: 'Douze mois', arrow: 'right' }] },
    { kind: 'letter' },
    { kind: 'letter' },
    { kind: 'clue', entries: [{ definition: 'Logement des oiseaux', arrow: 'right' }] },
    { kind: 'letter' },
    { kind: 'letter' },
    { kind: 'letter' },
    { kind: 'clue', entries: [{ definition: 'Préposition', arrow: 'right' }] },
    { kind: 'letter' },
    { kind: 'letter' },
    { kind: 'clue', entries: [{ definition: 'Sans vêtements', arrow: 'right' }] },
    { kind: 'letter' },
    { kind: 'letter' },
    { kind: 'clue', entries: [{ definition: 'Propre', arrow: 'right' }] },
    { kind: 'letter' },
    { kind: 'letter' },
    { kind: 'letter' },
    { kind: 'clue', entries: [{ definition: 'Conjonction de condition', arrow: 'right' }] },
    { kind: 'letter' },
    { kind: 'letter' },
    { kind: 'clue', entries: [{ definition: 'Ton, au féminin', arrow: 'right' }] },
    { kind: 'letter' },
    { kind: 'letter' },
    { kind: 'clue', entries: [{ definition: 'H₂O', arrow: 'right' }] },
    { kind: 'letter' },
    { kind: 'letter' },
    { kind: 'letter' },
  ],
};

export const MOCK_GRID_10_SOLUTION: GridSolution = {
  letters: [
    '',
    'C',
    'I',
    '',
    'P',
    'I',
    '',
    'S',
    'A',
    'L',
    '',
    'H',
    'A',
    '',
    'E',
    'T',
    '',
    'O',
    'S',
    'E',
    '',
    'R',
    'U',
    '',
    'R',
    'A',
    '',
    'L',
    'U',
    'E',
    '',
    'O',
    'N',
    '',
    'F',
    'I',
    '',
    'U',
    'N',
    'I',
    '',
    'N',
    'E',
    '',
    'O',
    'N',
    '',
    'T',
    'A',
    'U',
    '',
    'I',
    'L',
    '',
    'R',
    'E',
    '',
    'I',
    'R',
    'E',
    '',
    'Q',
    'I',
    '',
    'M',
    'A',
    '',
    'O',
    'S',
    'A',
    '',
    'U',
    'N',
    '',
    'A',
    'N',
    '',
    'N',
    'I',
    'D',
    '',
    'E',
    'N',
    '',
    'N',
    'U',
    '',
    'N',
    'E',
    'T',
    '',
    'S',
    'I',
    '',
    'T',
    'A',
    '',
    'E',
    'A',
    'U',
  ],
};

export type MockGridKey = '6' | '10';

export function buildMockGame(key: MockGridKey) {
  return key === '6'
    ? buildGame({ grid: MOCK_GRID_6, solution: MOCK_GRID_6_SOLUTION })
    : buildGame({ grid: MOCK_GRID_10, solution: MOCK_GRID_10_SOLUTION });
}
